### ISSUE TITLE
Getting Unfolding on Maven Central?

### ISSUE THREAD

**Issue by behr328** [tillnagel/unfolding#122]
The project looks great! Any chance we can get this up on Maven Central?

**Comment by tillnagel** [comment]
Great idea. What is needed for that? Would you be up for doing that (if possible)?

**Comment by GrgrLmml** [comment]
I am not sure about the process to get a project to Maven Central. What I did, I created a private repo on bintray [https://bintray.com/gregor-laemmel/maven/unfolding_maps](https://bintray.com/gregor-laemmel/maven/unfolding_maps). In order to use it you need to add the following into your pom.xml

     <repositories>
             <repository>
                 <id>extdeps</id>
                 <url>https://dl.bintray.com/gregor-laemmel/maven</url>
             </repository>
    </repositories>
    <dependencies>
            <dependency>
                 <groupId>org.processing</groupId>
                 <artifactId>pdf</artifactId>
                 <version>2.2.1</version>
            </dependency>
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-core</artifactId>
                <version>2.7</version>
            </dependency>
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-1.2-api</artifactId>
                <version>2.7</version>
            </dependency>
            <dependency>
                    <groupId>de.fhpotsdam</groupId>
                    <artifactId>unfolding</artifactId>
                    <version>0.9.6</version>
                    <type>jar</type>
            </dependency>
    </dependencies>

It is also possible to host maven repos directly on github  [see](http://stackoverflow.com/questions/14013644/hosting-a-maven-repository-on-github)
