### ISSUE TITLE
Masking examples not working

### ISSUE THREAD

**Issue by davidbambalan** [tillnagel/unfolding#163]
Hey, @tillnagel. I'm the same person on the Processing Discourse asking about masking. I followed your instructions, however, there is an error on `package de.fhpotsdam.unfolding.examples.mask;`. It shows an error `unexpected token: package`.

**Comment by tillnagel** [comment]
This is the continuation from https://discourse.processing.org/t/help-rounded-rectangle-unfolding-maps-masking-maps/11050

**Comment by tillnagel** [comment]
This is due to you using the Processing IDE. There, you need to simply remove this "package" - line. (This is used in Java for structuring larger projects).

However, it won't work in Processing at the moment. You would need to check out the full github repository, as I updated a MapShader in the core code. I won't be able to provide you with an updated Unfolding library for Processing right now, but will do so in the upcoming days.

**Comment by davidbambalan** [comment]
Removing the "package" line just makes a new error: `The file "test/mask.glsl" is missing or inaccessible, make sure the URL is valid or that the file has been added to your sketch and is readable.
NullPointerException
`

**Comment by tillnagel** [comment]
Yes. Please see the second part of my comment. 

Bear with me, as I am not on my work computer at the moment. This might take some days.

**Comment by tillnagel** [comment]
New beta 0.9.92 includes updates shader. Send us an e-mail if you want to get that version.

**Comment by davidbambalan** [comment]
Hello, where can I get the 0.9.92 update?

**Comment by tillnagel** [comment]
Send us an e-mail or give me any other option to privately contact you.

**Comment by davidbambalan** [comment]
david.bambalan@gmail.com is my email
